---
name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

    - name: Generate release notes
      run: |
        gh release create ${{github.ref_name}} --generate-notes --latest --notes "[Changelog](./CHANGELOG.md), [Documentation](./docs)"
      env:
        GH_TOKEN: ${{ github.token }}
